#!/bin/bash
git add . # tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name kristiansstendzenieks
git config --global user.email kristians.stendzenieks@edu.rtu.lv
#git commit -m "Class_04"
git commit -m "$1"
git push origin main
